#!/usr/bin/env sh

if [ -n "$PROCESSOR_ARCHITECTURE" -a "$PROCESSOR_ARCHITECTURE" == "AMD64" ]; then
  npx.cmd --no -- commitlint --edit "$1"
else
  . "$(dirname -- "$0")/_/husky.sh"
  npx --no -- commitlint --edit "$1"
fi
